apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multus
resources:
- ../../base
patches:
- path: delete-configmap.yaml
- path: delete-configmap-reference.yaml
- path: adjust-host-paths.yaml
- path: set-stable-image.yaml
