---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  customizeComponents: 
    patches:
    - resourceType: Deployment
      resourceName: virt-controller
      patch: '{"spec": {"replicas": 1}}'
      type: strategic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virt-operator
  namespace: kubevirt
spec:
  replicas: 1
