apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: multus
    server: https://kubernetes.default.svc
  project: default
  source:
    path: multus/overlays/lab
    repoURL: https://github.com/phoracek/tmp-argocd.git
    targetRevision: HEAD
  # ignoreDifferences:
  # - group: apiextensions.k8s.io
  #   kind: CustomResourceDefinition
  #   name: cdis.cdi.kubevirt.io
  #   jsonPointers:
  #   # Can't make it sync without this
  #   - /status
  #   - /spec
